title: KrknSec
header_pages:
  - index.md
url: "https://krkn-sec.github.io"
footer: 'follow us on <a href="https://twitter.com/KrknSec">twitter</a>'

remote_theme: b2a3e8/jekyll-theme-console
plugins:
- jekyll-remote-theme
